[package]
authors = ["dignifiedquire <me@dignifiedquire.com>", "Mike Lodder <redmike7@gmail.com>"]
categories = ["cryptography", "algorithms"]
description = "High performance implementation of BLS12 381"
documentation = "https://docs.rs/blstrs_plus"
edition = "2021"
homepage = "https://docs.rs/blstrs_plus"
license = "MIT/Apache-2.0"
name = "blstrs_plus"
readme = "README.md"
repository = "https://github.com/mikelodder7/blstrs"
version = "0.8.18"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dependencies]
ark-bls12-381 = { version = "0.4.0", optional = true }
ark-ec = { version = "0.4.2", optional = true }
ark-ff = { version = "0.4.2", optional = true }
ark-serialize = { version = "0.4.2", optional = true }
arrayref = "0.3"
blst = { version = "=0.3.12" }
elliptic-curve = { version = "0.13", features = ["hazmat"], default-features = false }
ff = "0.13"
group = { version = "0.13", features = ["tests"] }
num-bigint = { version = "0.4.5", optional = true }
num-traits = { version = "0.2.19", optional = true }
pairing_lib = { version = "0.23", package = "pairing" }
rand = { version = "0.8", optional = true }
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"], optional = true }
subtle = "2.5"
zeroize = { version = "1", features = ["zeroize_derive"] }

[dev-dependencies]
ark-poly = "0.4.2"
bls12_381_plus = "0.8"
rand_xorshift = "0.3"
serde_json = "1.0"
serde_bare = "0.5"
sha2 = "0.10"
hex = "0.4"

[features]
ark = ["ark-bls12-381", "ark-ec", "ark-ff", "ark-serialize", "num-bigint", "num-traits", "rand"]
default = ["hashing", "serde", "ark"]
hashing = ["elliptic-curve/hash2curve"]
portable = ["blst/portable"]
__private_bench = []
