[package]
authors = ["dignifiedquire <me@dignifiedquire.com>", "Mike Lodder <redmike7@gmail.com>"]
autobenches = false
categories = ["cryptography", "algorithms"]
description = "High performance implementation of BLS12 381"
documentation = "https://docs.rs/blstrs_plus"
edition = "2024"
homepage = "https://docs.rs/blstrs_plus"
license = "MIT/Apache-2.0"
name = "blstrs_plus"
readme = "README.md"
repository = "https://github.com/mikelodder7/blstrs"
version = "0.9.0-rc0"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[lib]
crate-type = ["rlib"]

[dev-dependencies]
ark-poly = "0.4.2"
hex = "0.4"
rand_xorshift = "0.3"
serde_bare = "0.5"
serde_json = "1.0"
sha2 = "0.10"
sha3 = "0.10"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = "0.8.2"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[[bench]]
name = "groups"
harness = false
required-features = ["groups"]

[dependencies.elliptic-curve]
version = "0.13.8"
features = ["hash2curve", "hazmat"]
default-features = false

[dependencies.ff]
version = "0.13.1"
default-features = false

[dependencies.group]
version = "0.13.0"
default-features = false
optional = true

[dependencies.pairing]
version = "0.23.0"
optional = true

[dependencies.rand_core]
version = "0.6.4"
default-features = false

[dependencies.subtle]
version = "2.5"
default-features = false

[dependencies.zeroize]
version = "1.8"
default-features = false

[dependencies.serde]
version = "1.0"
default-features = false
features = ["serde_derive"]

[dependencies.hex]
version = "0.4"
default-features = false

[dependencies.arrayref]
version = "0.3"

[dependencies.sha2]
version = "0.10"
default-features = false

[dependencies.ff_014]
package = "ff"
version = "0.14.0"
default-features = false

[dependencies.group_014]
package = "group"
version = "0.14.0"
default-features = false
optional = true

[dependencies.elliptic_curve_014]
package = "elliptic-curve"
version = "0.14.1"
default-features = false
features = ["arithmetic"]

[dependencies.elliptic-curve-tools]
version = "0.3.0"
default-features = false
features = ["legacy"]
optional = true

[dependencies.ark-bls12-381]
version = "0.4"
optional = true

[dependencies.ark-ec]
version = "0.4"
optional = true

[dependencies.ark-ff]
version = "0.4"
optional = true

[dependencies.ark-serialize]
version = "0.4"
optional = true

[dependencies.rand]
version = "0.8"
optional = true

[dependencies.num-bigint]
version = "0.4"
optional = true

[dependencies.num-traits]
version = "0.2"
optional = true

[features]
default = ["groups", "pairings", "alloc", "bits"]
bits = ["ff/bits", "ff_014/bits"]
expose-fields = ["groups"]
groups = ["group", "group_014"]
pairings = ["groups", "pairing"]
alloc = ["group/alloc", "group_014/alloc", "elliptic-curve-tools/alloc"]
ark = ["ark-bls12-381", "ark-ec", "ark-ff", "ark-serialize", "num-bigint", "num-traits", "rand", "std"]
std = []
